base_url = "https://thestaccato.github.io"

title = "Yash Sharma"
description = "Personal website"

compile_sass = true

[extra]
favicon_emoji = "&#x1f5a4"

socials = [
    { name = "linkedin", url = "https://linkedin.com" },
    { name = "email", url = "mailto:contact.untracked799@passinbox.com" },
    { name = "matrix", url = "https://matrix.org" },
    { name = "orcid", url = "https://orcid.org" },
    { name = "arxiv", url = "https://arxiv.org" },
    { name = "zenodo", url = "https://zenodo.org" },
    { name = "codeberg", url = "https://codeberg.org/thestaccato" },
    { name = "github", url = "https://github.com/thestaccato" },
    { name = "sourcehut", url = "https://sr.ht" },
    { name = "ko-fi", url = "https://sr.ht" },
]

